### ISSUE TITLE
arch-nspawn calls systemd-nspawn with invalid --bind-ro arguments

### ISSUE THREAD

**Issue by nastasie-octavian** [archlinux/devtools#29] opened 2019-10-29 11:06 UTC
I'm using aurutils to build and manage AUR packages and I haven't been able to build packages in a chroot since devtools updated a while back. I think the problem is with devtools so I'm opening the issue here.

I have this local repo in pacman.conf
> [aur_repo]
> SigLevel = Required TrustedOnly
> Server = file:///srv/http/pacman-cache/aur_repo/os/x86_64

When I try to build packages using aurutils with a chroot it fails with

> Failed to stat /srv/http/pacman-cache/$repo/os/$arch: No such file or directory

I digged around and fund that arch-nspawn calls systemd-nspawn with 

> --bind=/var/cache/pacman/pkg --bind-ro=/srv/http/pacman-cache/aur_repo/os/x86_64 --bind-ro=/srv/http/pacman-cache/$repo/os/$arch

I digged some more and I think that the problem was introduced in https://github.com/archlinux/devtools/commit/69112171e5de910331e46cf3f848866550125024 , specifically `cache_dirs+=("$line")`, the value stored in `$line` was obtained by replacing the actual repo name and arch from the Server line in pacman.conf with the $repo and $arch placeholder strings. `$line` doesn't indicate an actual folder on the filesystem so it isn't a valid argument to --bind.

**Comment by Foxboron** [comment] 2019-10-29 11:09
Duplicate of #14 i believe.

**Comment by bartoszek** [comment] 2019-10-30 07:22
I'm have slightly different configuration that it's working fine with current devtools :thinking: 
```sh
[aur]
SigLevel = Optional TrustAll
Server = file:///home/_pacman_cache/aur
```

**Comment by nastasie-octavian** [comment] 2019-10-31 16:13
I tried to write a fix for this. I tested it on my machine, for my config and it works, no more errors. It should probably fix #14 but I couldn't reproduce a similar error to test the fix.

**Comment by anthraxx** [comment] 2019-11-07 20:32
00671765296ad598f392df7a542dbfca48a6e7b7
f43a86ee8a3a3bfbdc32c2d70516d945afcd8515

**Closed by anthraxx** 2019-11-07 20:32 UTC

**Comment by nastasie-octavian** [comment] 2019-11-15 09:59
The bug is still present in master. The two commits above don't address it.

The commit that actually fixes the bug is this one https://github.com/eli-schwartz/devtools/commit/ea880ff3e5a58dd62b7c2162dcbb7c261ab4a3b2 - **arch-nspawn: rely on deduplication to avoid making multiple host_mirror mounts** - it changes what sed does and that fixes the problem.
